### ISSUE TITLE
Pending deprecation for Ingress extensions/v1beta1

### ISSUE THREAD

**Issue by ericgoedtel** [fabito/htk8s#17]
Getting a deprecation warning when using a contemporary Kubernetes release. Just a matter of reformatting the spec for the Ingress resources. The deprecation was introduced in 1.14 and will remove it in 1.22+.

I'd be happy to submit a patch for it if you want, its a boring manual change. I am fixing it in my fork but it has a bunch of of other implementation specific changes.

If interested, how would you like this fix delivered? Separate fork or just a PR? Or do you not care (which is totally fair) :D

**Comment by fabito** [comment]
Hey @ericgoedtel ,

Thanks for the heads up. A PR would be great ?
Is the warning coming from the Ingress ?
