### ISSUE TITLE
Volumes are not configured correctly for multi-node installation

### ISSUE THREAD

**Issue by spyridonas** [fabito/htk8s#5]
The volumes are mounted per machine, instead of using PersistantVolumeClaim (PVC).
The issue is that In case more than one node is running, it's possible for example radarr to run on machine 1 and the download to be done on machine 2, meaning that radarr on machine 1 cannot copy the download from machine 2.

I think a starting 20-40gb is good enough.

**Comment by fabito** [comment]
You are right. If you check the source code you will see that I tried that in the past (`pvc.yaml` and `volumes_patch.yaml`). I'm not really sure why I haven't used it though, I think I never bothered because my setup runs on a single node k3s.

Were you able to do some tests using PVC ?

**Comment by spyridonas** [comment]
After some research/digging around I found out k3s supports only Longhorn and only on AMD64. (https://rancher.com/docs/k3s/latest/en/storage/)  

While I was able to modify the relevant yaml files and they seem to work, the longhorn installation doesn't work meaning I'm unable to fully test it.
