### ISSUE TITLE
VPN support

### ISSUE THREAD

**Issue by krystofurr** [fabito/htk8s#6]
HI,

This setup looks great.  I am thinking of trying it out shortly once I get a new pi 4.  Any support for VPN inside the cluster ?

**Comment by fabito** [comment]
Yes, it is pretty solid/stable. I'm using an old laptop atm but a pi 4 might work as well.
I've never tried setting up a VPN It should be easy though. Which one you have in mind ?

**Comment by krystofurr** [comment]
Currently I use this setup for transmission from this repository below

https://github.com/haugene/docker-transmission-openvpn

They use OpenVPN.  This is so multiple providers can be used in the setup I believe. I wouldn't want the VPN network to be used with sonarr, jackett, etc.  Only transmission should be isolated on that network for security.  The others could be on the regular network. Or maybe provide the choice if possible.
