### ISSUE TITLE
Duplicate value: "torrent-tcp" - how did you deal with kustomize bug?

### ISSUE THREAD

**Issue by paranoid945** [fabito/htk8s#7]
https://github.com/kubernetes-sigs/kustomize/issues/2934

after excute kustomize command I got duplicate port in install.yaml:

```
        - containerPort: 51413
          name: torrent-tcp
          protocol: TCP
        - containerPort: 51413
          name: torrent-tcp
          protocol: TCP
```

**Comment by fabito** [comment]
What version of kustomize/kubectl are using ?

**Comment by paranoid945** [comment]
> What version of kustomize/kubectl are using ?

I believe the latest one.

**Comment by lackhoa** [comment]
I have this issue too, I'm using `v3.8.7`

**Comment by fabito** [comment]
Sorry @paranoid945  and @lackhoa , I cannot reproduce this error.
I just updated ArgoCD and all the images and the manifests were applied successfully.
How exactly are you trying to install ?

**Comment by lackhoa** [comment]
@fabito I don't know about OP, but I have created [an issue](https://github.com/kubernetes-sigs/kustomize/issues/3513) with my particular problematic manifest and it was resolved.
So no problem from my side.

**Comment by fabito** [comment]
I also added this github actions for manifests verfication: https://github.com/fabito/htk8s/runs/2055640038?check_suite_focus=true
And they all seem good.
